# Generated by Django 4.2.13 on 2024-08-11 09:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_private', models.BooleanField(default=True, verbose_name='Is Private')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('CONTRIBUTOR', 'CONTRIBUTOR')], default='OPEN', max_length=50, verbose_name='User Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='feedback.company', verbose_name='Company')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'get_latest_by': 'modified_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=50, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='feedback.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
            },
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('channel_value', models.CharField(max_length=255, verbose_name='Channel Value')),
                ('channel_type', models.CharField(choices=[('PHONE', 'PHONE'), ('EMAIL', 'EMAIL')], default='Undefined', max_length=50, verbose_name='Channel Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optouts', to='feedback.company', verbose_name='Company')),
            ],
            options={
                'get_latest_by': 'modified_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=None, verbose_name='Image')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('UNDER_REVIEW', 'UNDER REVIEW'), ('PLANNED', 'PLANNED'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=50, verbose_name='Status')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags')),
                ('category', models.CharField(choices=[('Undefined', 'Undefined'), ('Feature', 'Feature'), ('Bug', 'Bug'), ('Enhancement', 'Enhancement'), ('Task', 'Task')], default='Undefined', max_length=50, verbose_name='Category')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.board', verbose_name='Board')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.company', verbose_name='Company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.roadmap', verbose_name='Roadmap')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('created_by', models.UUIDField(verbose_name='Created By')),
                ('modified_by', models.UUIDField(blank=True, null=True, verbose_name='Modified By')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))),
                ('email_id', models.CharField(max_length=255, verbose_name='Emaild ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('source', models.CharField(choices=[('FEEDBACK', 'FEEDBACK'), ('CONTACT', 'CONTACT'), ('SUBSCRIBE', 'SUBSCRIBE')], default='SUBSCRIBE', max_length=50, verbose_name='Source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='feedback.company', verbose_name='Company')),
            ],
            options={
                'get_latest_by': 'modified_on',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='feedback.company', verbose_name='Company'),
        ),
    ]
